/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.ferracini;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException, InterruptedException {
        System.out.println(new App().getGreeting());
        Commands commands = new Commands();
        commands.runCommandProcessBuilder();
    }
}
